# Uncomment the next line to define a global platform for your project


target 'HitList' do
  # Comment the next line if you don't want to use dynamic frameworks

  platform :ios, '9.0'

  use_frameworks!

  # Pods for HitList
  pod 'AFNetworking', '~> 4.0' 
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
end
