# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountriesTraveller' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountriesTraveller
  pod 'Alamofire', '~> 5.2'
  pod 'FirebaseUI/Auth'
  pod 'SVProgressHUD'
  pod "FlagPhoneNumber"
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  
end
