# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FootballManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FootballManager
  pod 'AFNetworking', '~> 4.0' 
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'SwiftyJSON'
end
